default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: unter_development

test: &test
  <<: *default
  database: unter_test
  
production:
  <<: *default
  database: unter_production
  username: unter
  password: <%= ENV['UNTER_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
